### ISSUE TITLE
After using this layer, sls deploy fails with InvalidParameterValueException;

### ISSUE THREAD

**Issue by kesavab** [luisdemarchi/serverless-esm-layer#1]
After installing the plugin, sls deploy is failing with error. I believe this is because the zip is modified.
An error occurred: QueryLambdaVersionWkb2ihkztXKURNCHXWHqD4Js3IGUtzfeA3cgEYzXkZk - CodeSHA256 (AtnhX+0WdwN04fri48W/FOCssmclUKx+BWNiCKchI10=) is different from current CodeSHA256 in $LATEST (1ZA02Yj5UQpjSvUy+G2b5SevE3XAlIZjNOY/MCL19Xo=). Please try again with the CodeSHA256 in $LATEST. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: de03364b-7c0f-46d7-86b6-1468f1e41e04; Proxy: null).

**Comment by luisdemarchi** [comment]
@kesavab sorry for the delay. I will analyze the error.

**Comment by luisdemarchi** [comment]
@kesavab  The problem was in the synchronization of the calls. A fix was made and tested. Version 1.0.5
